[package]
name = "fuel-core-upgradable-executor"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = ["blockchain", "fuel", "fuel-vm", "upgradable"]
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
description = "Fuel Block Upgradable Executor"
build = "build.rs"

[features]
default = ["std"]
std = ["fuel-core-executor/std", "fuel-core-storage/std", "fuel-core-types/std"]
wasm-executor = [
    "dep:anyhow",
    "dep:derive_more",
    "dep:postcard",
    "dep:tracing",
    "dep:fuel-core-wasm-executor",
    "dep:wasmtime",
]
test-helpers = ["fuel-core-storage/test-helpers", "fuel-core-types/test-helpers"]
limited-tx-count = ["fuel-core-executor/limited-tx-count"]
fault-proving = [
    "fuel-core-executor/fault-proving",
    "fuel-core-storage/fault-proving",
    "fuel-core-types/fault-proving",
    "fuel-core-wasm-executor?/fault-proving",
]

[dependencies]
anyhow = { workspace = true, optional = true }
derive_more = { workspace = true, optional = true }
fuel-core-executor = { workspace = true }
fuel-core-storage = { workspace = true, features = ["std"] }
fuel-core-types = { workspace = true, features = ["std"] }
fuel-core-wasm-executor = { workspace = true, features = [
  "std",
], optional = true }
futures = { workspace = true }
parking_lot = { workspace = true }
postcard = { workspace = true, optional = true }
tracing = { workspace = true, optional = true }
wasmtime = { version = "36.0.3", default-features = false, features = [
  "cache",
  "cranelift",
  "parallel-compilation",
  "pooling-allocator",
  "runtime",
], optional = true }

[build-dependencies]
fuel-core-wasm-executor = { workspace = true, optional = true, default-features = false }

[dev-dependencies]
anyhow = { workspace = true }
fuel-core-storage = { workspace = true, features = ["test-helpers"] }
fuel-core-types = { workspace = true, features = ["test-helpers"] }
