[package]
name = "fuel-core-upgradable-executor"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = ["blockchain", "fuel", "fuel-vm", "upgradable"]
license = { workspace = true }
repository = { workspace = true }
description = "Fuel Block Upgradable Executor"
build = "build.rs"

[dependencies]
anyhow = { workspace = true, optional = true }
fuel-core-executor = { workspace = true }
fuel-core-storage = { workspace = true }
fuel-core-types = { workspace = true }
fuel-core-wasm-executor = { workspace = true, optional = true }
parking_lot = { workspace = true, optional = true }
postcard = { workspace = true, optional = true }
tracing = { workspace = true, optional = true }
wasmtime = { version = "18.0.1", default-features = false, features = [
  "cache",
  "cranelift",
  "parallel-compilation",
  "pooling-allocator",
  "runtime",
], optional = true }

[dev-dependencies]
anyhow = { workspace = true }
fuel-core-storage = { workspace = true, features = ["test-helpers"] }
fuel-core-types = { workspace = true, features = ["test-helpers"] }
ntest = "0.9.2"

[build-dependencies]
fuel-core-wasm-executor = { workspace = true, optional = true, default-features = false }

[features]
default = ["std"]
std = ["fuel-core-executor/std", "fuel-core-storage/std", "fuel-core-types/std"]
smt = [
  "fuel-core-storage/smt",
  "fuel-core-executor/smt",
  "fuel-core-wasm-executor?/smt",
]
wasm-executor = [
  "dep:anyhow",
  "dep:parking_lot",
  "dep:postcard",
  "dep:tracing",
  "dep:fuel-core-wasm-executor",
  "dep:wasmtime",
  "fuel-core-types/wasm-executor",
]
test-helpers = [
  "fuel-core-storage/test-helpers",
  "fuel-core-types/test-helpers",
]
