[package]
name = "graph"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0"
async-trait = "0.1.50"
async-stream = "0.3"
atomic_refcell = "0.1.13"
bigdecimal = { version = "0.1.0", features = ["serde"] }
bytes = "1.0.1"
cid = "0.11.0"
diesel = { version = "1.4.8", features = ["postgres", "serde_json", "numeric", "r2d2", "chrono"] }
diesel_derives = "1.4"
chrono = "0.4.31"
envconfig = "0.10.0"
Inflector = "0.11.3"
isatty = "0.1.9"
reqwest = { version = "0.11.18", features = ["json", "stream", "multipart"] }
ethabi = "17.2"
hex = "0.4.3"
http = "0.2.3"
futures = "0.1.21"
graphql-parser = "0.4.0"
humantime = "2.1.0"
lazy_static = "1.4.0"
num-bigint = { version = "^0.2.6", features = ["serde"] }
num_cpus = "1.16.0"
num-traits = "=0.2.17"
rand = "0.8.4"
regex = "1.5.4"
semver = { version = "1.0.20", features = ["serde"] }
serde = { version = "1.0.126", features = ["rc"] }
serde_derive = "1.0.125"
serde_json = { version = "1.0", features = ["arbitrary_precision"] }
serde_regex = "1.1.0"
serde_yaml = "0.9.21"
slog = { version = "2.7.0", features = ["release_max_level_trace", "max_level_trace"] }
# TODO: This should be reverted to the latest version once it's published
# stable-hash_legacy = { version = "0.3.3", package = "stable-hash" }
# stable-hash = { version = "0.4.2" }
stable-hash = { git = "https://github.com/graphprotocol/stable-hash", branch = "main"}
stable-hash_legacy = { git = "https://github.com/graphprotocol/stable-hash", branch = "old", package = "stable-hash" }
strum = "0.21.0"
strum_macros = "0.25.3"
slog-async = "2.5.0"
slog-envlogger = "2.1.0"
slog-term = "2.7.0"
petgraph = "0.6.4"
tiny-keccak = "1.5.0"
tokio = { version = "1.34.0", features = ["time", "sync", "macros", "test-util", "rt-multi-thread", "parking_lot"] }
tokio-stream = { version = "0.1.14", features = ["sync"] }
tokio-retry = "0.3.0"
toml = "0.8.8"
url = "2.5.0"
prometheus = "0.13.3"
priority-queue = "0.7.0"
tonic = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }

futures03 = { version = "0.3.1", package = "futures", features = ["compat"] }
wasmparser = "0.78.2"
thiserror = "1.0.25"
parking_lot = "0.12.1"
itertools = "0.12.0"

# Our fork contains patches to make some fields optional for Celo and Fantom compatibility.
# Without the "arbitrary_precision" feature, we get the error `data did not match any variant of untagged enum Response`.
web3 = { git = "https://github.com/graphprotocol/rust-web3", branch = "graph-patches-onto-0.18", features = ["arbitrary_precision"] }
serde_plain = "1.0.2"

[dev-dependencies]
clap = { version = "3.2.25", features = ["derive", "env"] }
maplit = "1.0.2"
hex-literal = "0.4"

[build-dependencies]
tonic-build = { workspace = true }
