[package]
name = "fuel-core-executor"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = ["blockchain", "fuel", "fuel-vm"]
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
description = "Fuel Block Executor"

[features]
default = ["std"]
std = ["fuel-core-types/std", "fuel-core-storage/std"]
alloc = ["fuel-core-types/alloc", "fuel-core-storage/alloc"]
test-helpers = ["fuel-core-types/test-helpers", "fuel-core-storage/test-helpers"]
u32-tx-count = ["fuel-core-types/u32-tx-pointer"]
fault-proving = ["fuel-core-types/fault-proving", "fuel-core-storage/fault-proving"]

[dependencies]
anyhow = { workspace = true }
fuel-core-storage = { workspace = true, default-features = false, features = [
  "alloc",
] }
fuel-core-syscall = { workspace = true, default-features = false, features = [
  "alloc",
] }
fuel-core-types = { workspace = true, default-features = false, features = [
  "alloc",
] }
parking_lot = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true, default-features = false }
tracing = { workspace = true }

[dev-dependencies]
fuel-core-storage = { workspace = true, features = ["test-helpers"] }
fuel-core-trace = { path = "../../trace" }
fuel-core-types = { workspace = true, features = ["test-helpers"] }
