[package]
name = "fuel-core-client"
version = { workspace = true }
authors = { workspace = true }
categories = ["concurrency", "cryptography::cryptocurrencies", "emulators"]
edition = { workspace = true }
homepage = { workspace = true }
keywords = ["blockchain", "cryptocurrencies", "fuel-vm", "vm"]
license = { workspace = true }
repository = { workspace = true }
description = "Tx client and schema specification."

[dependencies]
anyhow = { workspace = true }
cynic = { version = "2.2.1", features = ["http-reqwest"] }
derive_more = { version = "0.99" }
eventsource-client = "0.10.2"
fuel-core-types = { version = "0.16.1", path = "../types", features = ["serde"] }
futures = "0.3"
hex = "0.4"
# Included to enable webpki in the eventsource client
hyper-rustls = { version = "0.22", features = ["webpki-tokio"] }
itertools = { workspace = true }
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { version = "1.0", features = ["raw_value"] }
tai64 = { version = "4.0", features = ["serde"] }
thiserror = "1.0"

[dev-dependencies]
insta = { workspace = true }

[build-dependencies]
schemafy_lib = { version = "0.5", optional = true }
serde_json = { version = "1.0", features = ["raw_value"], optional = true }

[features]
test-helpers = []
dap = ["schemafy_lib", "serde_json"]
