[package]
edition = { workspace = true }
name = "xtask"
version = "0.0.0"
license = { workspace = true }
publish = false
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { workspace = true, features = ["env", "derive"] }
fuel-core = { path = "../crates/fuel-core", default-features = false, features = [
  "test-helpers",
] }
