[package]
name = "substreams-trigger-filter"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
hex = { version = "0.4", default-features = false }
prost.workspace = true 
substreams = "0.5"
substreams-entity-change = "1.3"
substreams-near-core = "0.10.1"
anyhow = "1"

trigger-filters.path = "../trigger-filters"

[build-dependencies]
tonic-build = { version = "0.8.4", features = ["prost"] }

