[package]
name = "indexer-demo"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ['cdylib']

[dependencies]
fuels-core = { path = "../../../fuels-rs/fuels-core", features=["no-std"] }
fuel-indexer = { path = "../../fuel-indexer/lib" }
fuel-indexer-derive = { path = "../../fuel-indexer/derive" }
fuels-abigen-macro = { path = "../../../fuels-rs/fuels-abigen-macro" }
serde = { version = "1.0", default-features = false, features = ["derive"] }
