# Default values for fuel core for environment
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

app:
  name: ${fuel_core_service_name}
  selector_name: ${fuel_core_selector_name}
  replicas: ${fuel_core_pod_replicas}
  http_port: 80
  target_port: 4000
  peering_port: 30333
  human_logging: ${fuel_core_human_logging}
  rust_log: ${fuel_core_rust_log}
  utxo_validation: ${fuel_core_utxo_validation}
  vm_backtrace: ${fuel_core_vm_backtrace}
  min_gas_price: "${fuel_core_min_gas_price}"
  network_name: ${fuel_core_network_name}
  poa_instant: "${fuel_core_poa_instant}"
  poa_interval_period: "${fuel_core_poa_interval_period}"
  max_block_size: "${fuel_core_max_buffer_size}"
  max_headers_per_request: "${fuel_core_max_headers_per_request}"
  max_database_cache_size: "${fuel_core_max_database_cache_size}"
  max_transmit_size: "${fuel_core_max_buffer_size}"
  heartbeat_check_interval: "${fuel_core_heartbeat_check_interval}"
  heartbeat_max_avg_interval: "${fuel_core_heartbeat_max_avg_interval}"
  heartbeat_max_time_since_last: "${fuel_core_heartbeat_max_time_since_last}"
  sync_block_stream_size: "${fuel_core_sync_block_stream_size}"
  sync_header_batch_size: "${fuel_core_sync_header_batch_size}"
  p2p_key: ${fuel_core_p2p_key}
  allow_private_addresses: ${fuel_core_allow_private_addresses}
  reserved_nodes_only_mode: ${fuel_core_reserved_only}
  reserved_nodes: ${fuel_core_reserved_nodes}
  bootstrap_nodes: ${fuel_core_bootstrap_nodes}
  relayer: ${fuel_core_relayer}
  relayer_v2_listening_contracts: ${fuel_core_relayer_v2_listening_contracts}
  relayer_da_finalization: "${fuel_core_relayer_da_finalization}"
  relayer_da_deploy_height: "${fuel_core_relayer_da_deploy_height}"
  relayer_log_page_size: "${fuel_core_relayer_log_page_size}"
  relayer_min_duration_s: "${fuel_core_relayer_min_duration_s}"
  relayer_eth_sync_call_freq_s: "${fuel_core_relayer_eth_sync_call_freq_s}"
  relayer_eth_sync_log_freq_s: "${fuel_core_relayer_eth_sync_log_freq_s}"
  sentry_enabled: ${fuel_core_sentry_enabled}
  pyroscope_url: "${fuel_core_pyroscope_url}"
  pprof_sample_rate: "${fuel_core_pprof_sample_rate}"
  image:
    repository: ${fuel_core_image_repository}
    tag: ${fuel_core_image_tag}
    pullPolicy: Always
  volume: 
    pvname: ${fuel_core_pv_name}
    mountPath: /mnt/db/
    claimname: ${fuel_core_pvc_name}
    pvc_clone_enabled: ${fuel_core_pvc_clone_enabled}
    pvc_clone_snapshot_id: ${fuel_core_pvc_snapshot_id}
    storageclass: ${pvc_storage_class}
    storagerequests: ${pvc_storage_requests}
    accessmodes: ReadWriteOnce
  resources:
    cpu_requests: ${fuel_core_cpu_requests}
    memory_requests: ${fuel_core_memory_requests}
    cpu_limits: ${fuel_core_cpu_limits}
    memory_limits: ${fuel_core_memory_limits}
  prometheus:
    enabled: ${fuel_core_prometheus_enabled}
    helm_release_name: ${fuel_core_prometheus_helm_release_name}
