[package]
name = "fuel-gas-price-analysis"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
csv = "1.3.0"
fuel-gas-price-algorithm = { path = ".." }
plotters = "0.3.5"
rand = "0.8.5"
rand_distr = "0.4.3"
serde = { version = "1.0.209", features = ["derive"] }
