[package]
name = "fuel-core-relayer"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = ["blockchain", "fuel", "fuel-vm"]
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
description = "Fuel Relayer"

[features]
test-helpers = ["fuel-core-provider"]

[dependencies]
alloy-primitives = { workspace = true }
alloy-provider = { workspace = true }
alloy-rpc-types-eth = { workspace = true }
alloy-sol-types = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
enum-iterator = { workspace = true }
fuel-core-provider = { workspace = true, optional = true }
fuel-core-services = { workspace = true }
fuel-core-storage = { workspace = true, features = ["std"] }
fuel-core-types = { workspace = true, features = ["std"] }
futures = { workspace = true }
once_cell = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
tokio = { workspace = true, features = ["macros"] }
tracing = { workspace = true }
url = { workspace = true }

[dev-dependencies]
fuel-core-provider = { path = "../../provider" }
fuel-core-relayer = { path = "", features = ["test-helpers"] }
fuel-core-services = { path = "../../services", features = ["test-helpers"] }
fuel-core-storage = { path = "../../storage", features = ["test-helpers"] }
fuel-core-trace = { path = "../../trace" }
mockall = { workspace = true }
rand = { workspace = true }
test-case = { workspace = true }
tokio = { workspace = true, features = ["macros", "test-util"] }
