[package]
authors = { workspace = true }
categories = ["cryptography::cryptocurrencies"]
description = "A Tokio tracing initializer for testing"
edition = { workspace = true }
homepage = { workspace = true }
keywords = [
  "blockchain",
  "cryptocurrencies",
  "fuel-client",
  "fuel-core",
  "fuel-tracing",
  "tracing",
]
license = { workspace = true }
name = "fuel-core-trace"
publish = false
repository = { workspace = true }
version = { workspace = true }

[dependencies]
ctor = "0.1"
tracing = { workspace = true }
tracing-appender = "0.2"
tracing-subscriber = { workspace = true, features = ["env-filter"] }
