[package]
name = "fuel-indexer-schema"
version = "0.0.0"
edition = "2021"
license = "BUSL-1.1"
publish = false
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "1.4", optional = true, features = ["postgres", "serde_json"] }
fuel-tx = { version = "0.6", default-features = false }
fuel-types = { version = "0.3", default-features = false }
graphql-parser = "0.3"
itertools = { version = "0.10", optional = true }
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde-scale = "0.2"
sha2 = "0.9"
thiserror = { version = "1.0", optional = true }

[dev-dependencies]
insta = "1.8"

[features]
default = ["fuel-types/serde-types-minimal"]
db-models = ["use-std", "itertools", "thiserror"]
use-std = ["fuel-types/default", "fuel-types/serde-types", "diesel"]
