[package]
name = "graph-chain-ethereum"
version.workspace = true
edition.workspace = true

[dependencies]
envconfig = "0.10.0"
futures = "0.1.21"
http = "0.2.4"
jsonrpc-core = "18.0.0"
graph = { path = "../../graph" }
lazy_static = "1.2.0"
serde = "1.0"
prost = { workspace = true }
prost-types = { workspace = true }
dirs-next = "2.0"
anyhow = "1.0"
tiny-keccak = "1.5.0"
hex = "0.4.3"
semver = "1.0.20"

itertools = "0.12.0"

graph-runtime-wasm = { path = "../../runtime/wasm" }
graph-runtime-derive = { path = "../../runtime/derive" }

[dev-dependencies]
base64 = "0.20.0"
uuid = { version = "1.6.1", features = ["v4"] }

[build-dependencies]
tonic-build = { workspace = true }
